#!/usr/bin/env bash
# Local install helper. It does not fetch dependencies or run package managers.
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
ADAPTER="$ROOT/kilo-plugin/work-journal.js"

usage() {
  cat <<'EOF'
work-journal installer
  scripts/install.sh claude                 print Claude Code marketplace commands
  scripts/install.sh codex                  print Codex marketplace commands
  scripts/install.sh kilo --project [dir]   create dir/.kilo/kilo.jsonc if absent
  scripts/install.sh kilo --global          create ~/.config/kilo/kilo.jsonc if absent
  scripts/install.sh opencode --project [dir] create dir/.opencode/plugins wrapper
  scripts/install.sh opencode --global      create ~/.config/opencode/plugins wrapper
  scripts/install.sh doctor                 run journal doctor --strict

The Kilo installer only creates a missing config file. The OpenCode installer
only creates a missing local plugin wrapper. Existing files are not merged.
EOF
}

file_url() {
  case "$ADAPTER" in
    *[[:space:]]*)
      printf '%s\n' "adapter path contains whitespace; move the checkout or configure this file URL manually: $ADAPTER" >&2
      return 1
      ;;
  esac
  printf 'file://%s' "$ADAPTER"
}

kilo_config_dir() {
  if [ "${1:-}" = "--global" ]; then
    printf '%s' "${XDG_CONFIG_HOME:-$HOME/.config}/kilo"
  else
    printf '%s' "${2:-$PWD}/.kilo"
  fi
}

opencode_plugin_dir() {
  if [ "${1:-}" = "--global" ]; then
    printf '%s' "${XDG_CONFIG_HOME:-$HOME/.config}/opencode/plugins"
  else
    printf '%s' "${2:-$PWD}/.opencode/plugins"
  fi
}

write_kilo_config() {
  local scope="$1" dir target url
  shift
  dir="$(kilo_config_dir "$scope" "${1:-$PWD}")"
  target="$dir/kilo.jsonc"
  url="$(file_url)" || return 1

  mkdir -p "$dir" || return 1
  if [ -f "$target" ]; then
    if grep -Fq "$ADAPTER" "$target" 2>/dev/null || grep -Fq "$url" "$target" 2>/dev/null; then
      printf 'already configured: %s\n' "$target"
      return 0
    fi
    cat <<EOF
config exists, not editing: $target

Add this plugin entry manually:

{
  "plugin": ["$url"]
}
EOF
    return 2
  fi

  cat > "$target" <<EOF
{
  "plugin": ["$url"]
}
EOF
  printf 'wrote %s\n' "$target"
}

write_opencode_plugin() {
  local scope="$1" dir target url
  shift
  dir="$(opencode_plugin_dir "$scope" "${1:-$PWD}")"
  target="$dir/work-journal.js"
  url="$(file_url)" || return 1

  mkdir -p "$dir" || return 1
  if [ -f "$target" ]; then
    if grep -Fq "$url" "$target" 2>/dev/null; then
      printf 'already configured: %s\n' "$target"
      return 0
    fi
    cat <<EOF
plugin wrapper exists, not editing: $target

Use this wrapper if you want to replace it manually:

export { WorkJournal } from "$url";
EOF
    return 2
  fi

  cat > "$target" <<EOF
// Generated by work-journal. Re-run scripts/install.sh if the checkout moves.
export { WorkJournal } from "$url";
EOF
  printf 'wrote %s\n' "$target"
}

cmd="${1:-}"; [ $# -gt 0 ] && shift
case "$cmd" in
  claude)
    cat <<'EOF'
/plugin marketplace add 7KiLL/claude-work-journal
/plugin install work-journal@claude-work-journal
EOF
    ;;
  codex)
    cat <<'EOF'
codex plugin marketplace add 7KiLL/claude-work-journal --sparse .agents/plugins
codex plugin add work-journal@claude-work-journal
EOF
    ;;
  kilo|opencode)
    scope="${1:---project}"
    if [ "$cmd" = kilo ]; then
      case "$scope" in
        --global) write_kilo_config --global ;;
        --project) shift; write_kilo_config --project "${1:-$PWD}" ;;
        *) echo "usage: scripts/install.sh kilo --project [dir] | --global"; exit 1 ;;
      esac
    else
      case "$scope" in
        --global) write_opencode_plugin --global ;;
        --project) shift; write_opencode_plugin --project "${1:-$PWD}" ;;
        *) echo "usage: scripts/install.sh opencode --project [dir] | --global"; exit 1 ;;
      esac
    fi
    ;;
  doctor)
    WORK_JOURNAL_SUMMARIZER="${WORK_JOURNAL_SUMMARIZER:-cat >/dev/null; printf '%s\n' SKIP}" bash "$ROOT/journal.sh" doctor --strict
    ;;
  ""|-h|--help|help)
    usage
    ;;
  *)
    echo "unknown installer target: $cmd"
    echo
    usage
    exit 1
    ;;
esac
